frameworkVersion: '^3.38.0'

service: ${self:custom.appPrefix}

provider:
  name: aws
  region: ${opt:region}
  stage: ${opt:stage}
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 256
  stackTags:
    voxnest:billing:app: ${self:custom.appPrefix}
  environment:
    STAGE: ${opt:stage}

custom:
  domain: ${param:domain, ''}
  zoneId: ${param:zoneId, ''}
  appPrefix: vn-lab-ppm-website
  s3Sync:
    - bucketNameKey: WebsiteBucketNameOutputKey
      deleteRemoved: false
      localDir: dist
      acl: public-read

package:
  patterns:
    - '!.*'
    - '!README.md'
    - '!serverless*.yml'
    - '!tailwind.config.js'
    - '!dist'
    - '!deployment'
    - '!src'
    - '!public'

plugins:
  - serverless-s3-sync

resources:
  - ${file(deployment/resources/s3.yml)}
  - ${file(deployment/resources/cloudfront.yml)}
  - ${file(deployment/resources/domain.yml)}

  - Outputs:
      WebsiteBucketNameOutputKey:
        Value: !Ref WebsiteBucket
